### ISSUE TITLE
FEAT: Setup basic settings and bottom navigation

### ISSUE THREAD

**Issue by world2222** [world2222/Remember#1]
# Description
* Setup basic environment settings
* Make a navigation bar that allows the user to navigate to multiple pages like home, random, review, and my page screen.

# Todo
- [x] Add essential dependencies
- [x] Make a navigation bar
- [x] Set the screens that belongs to each navigation bar items
